import type { GearId } from "../../../convex/lib/rpg";
import type { PixelMap } from "../pixels";

/**
 * Gear (#162, lib/rpg.ts `GEAR`) in our own pixels, 12 × 12: three hats, three tools and three
 * charms at each rarity, drawn wherever gear shows: the cabin's slots, the stall's shelf and a
 * run's results. Gear is never drawn on the hedgehog (PostHog's accessories are its only looks).
 */
export const GEAR_ART: Record<GearId, PixelMap> = {
  dune_hat: {
    rows: [
      "............",
      "............",
      "....kkkk....",
      "...kaaaak...",
      "...kaaaak...",
      "...kDDDDk...",
      ".kkkaaaakkk.",
      "kaaaaaaaaaak",
      "kAAAAAAAAAAk",
      ".kkkkkkkkkk.",
      "............",
      "............",
    ],
  },
  brass_trowel: {
    rows: [
      "........kk..",
      ".......klk..",
      "......kllk..",
      ".....kllck..",
      "....klllk...",
      "...kllek....",
      "...kkkk.....",
      "..kbk.......",
      ".kbk........",
      "kbk.........",
      "kk..........",
      "............",
    ],
  },
  amber_charm: {
    rows: [
      "..k......k..",
      "...k....k...",
      "....k..k....",
      ".....kk.....",
      ".....kk.....",
      "....kllk....",
      "...kllclk...",
      "...klllek...",
      "...kleeek...",
      "....keek....",
      ".....kk.....",
      "............",
    ],
  },
  scout_cap: {
    rows: [
      "............",
      "............",
      "....kkkk....",
      "...kggggk...",
      "..kgguggk...",
      "..kggggggk..",
      "..kGGGGGGk..",
      "..kkkkkkkggk",
      ".........kkk",
      "............",
      "............",
      "............",
    ],
  },
  iron_spade: {
    rows: [
      "........kkk.",
      ".......kmmmk",
      "......kmmcmk",
      "......kmmmMk",
      ".....kkMMMk.",
      "....kbkkkk..",
      "...kbk......",
      "..kbk.......",
      ".kbk........",
      "kkbk........",
      "kbkk........",
      "kk..........",
    ],
  },
  moon_pendant: {
    rows: [
      "..k......k..",
      "...k....k...",
      "....k..k....",
      ".....kk.....",
      "....kkkkk...",
      "...kccccck..",
      "..kccmkkk...",
      "..kcck......",
      "..kccmkkk...",
      "...kccccck..",
      "....kkkkk...",
      "............",
    ],
  },
  archivist_hood: {
    rows: [
      ".....kk.....",
      "....kvvk....",
      "...kvvvvk...",
      "..kvvvvvvk..",
      "..kvkkkkvk..",
      ".kvkdddkvk..",
      ".kvkdddkvk..",
      ".kvvkkkvvk..",
      "kvvvvvvvvvk.",
      "kpvvvvvvvpk.",
      ".kkkkkkkkk..",
      "............",
    ],
  },
  sap_blade: {
    rows: [
      "..........kk",
      ".........kyk",
      "........kyck",
      ".......kyyk.",
      "......kyyk..",
      ".....kyyk...",
      "..kkkyyk....",
      "..kBkyk.....",
      "...kBk......",
      "..kbkBk.....",
      ".kbk.kk.....",
      "kkk.........",
    ],
  },
  heart_stone: {
    rows: [
      "..k......k..",
      "...k....k...",
      "....k..k....",
      ".....kk.....",
      "..kkkkkkk...",
      ".keeckeeek..",
      ".keceeeeek..",
      ".keeeeeeek..",
      "..keeeeEk...",
      "...keeEk....",
      "....kEk.....",
      ".....k......",
    ],
  },
  crown_of_leaves: {
    rows: [
      "............",
      "............",
      "..k..kk..k..",
      ".kuk.kuk.kuk",
      ".kguk.kgukgk",
      "kggugkgguggk",
      "kgGggggggGgk",
      "kGGGGGGGGGGk",
      ".kkkkkkkkkk.",
      "............",
      "............",
      "............",
    ],
  },
  lantern_staff: {
    rows: [
      "......kkk...",
      ".....kbbbk..",
      ".....klllk..",
      ".....klclk..",
      ".....klllk..",
      "......kbk...",
      ".....kbk....",
      "....kbk.....",
      "...kbk......",
      "..kbk.......",
      ".kbk........",
      "kkk.........",
    ],
  },
  first_seed: {
    rows: [
      "..k......k..",
      "...k....k...",
      "....k..k....",
      ".....kk.....",
      ".....yk.....",
      "....kyyk....",
      "...ksyysk...",
      "...kssssk...",
      "...ksbbsk...",
      "....kbbk....",
      ".....kk.....",
      "............",
    ],
  },
};
